version: "2"
services:
  frontend:
    image: node:7.7
    working_dir: /frontend
    command: npm start
    volumes:
        - ./frontend:/frontend
    ports:
        - "3000:3000"
  server:
    image: node:7.7
    working_dir: /server
    command: npm start
    volumes:
        - ./server:/server
    ports:
        - "8000:8000"
        - "5858:5858"
    environment:
        NODE_ENV: ${NODE_ENV}
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - /data/db
